Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,4 +17,4 @@ jobs:
       - run: npm run vercel-build
       - run: npm run postbuild
       - name: Check dist output
-        run: ls -la dist || echo "ERROR: dist directory not found"
+        run: ls -la dist || echo "ERROR:dist directory not found"
